version: '3.5'

services:
    api-1:
      build: ./api
      networks: 
        - superweb
      container_name: api-1
      environment:
        - SERVER=api-1

    api-2:
      build: ./api
      networks: 
        - superweb
      container_name: api-2
      environment:
        - SERVER=api-2

    nginx:
      build: ./nginx
      depends_on: 
        - api-1
        - api-2
      networks: 
        - superweb
      ports:
        - 80:80
      container_name: nginx
networks:
  superweb:
    name: superweb
    driver: bridge