version: '3'

services:
    node-1:
      build: ./api
      networks: 
        - superweb
      container_name: node-1

    node-2:
      build: ./api
      networks: 
        - superweb
      container_name: node-2

    nginx:
      build: ./nginx
      depends_on: 
        - node-1
        - node-2
      networks: 
        - superweb
      ports:
        - 8082:8080
      container_name: ngnix
networks:
  superweb:
    driver: bridge